require('dotenv').config();
const express = require('express');
const cors = require('cors');
const mongoose = require('mongoose');
const authRoutes = require('./routes/auth');
const leadsRoutes = require('./routes/leads');
const newsletterRoutes = require('./routes/newsletter');
const adminRoutes = require('./routes/admin');
const app = express();
app.use(cors()); app.use(express.json());
const PORT = process.env.PORT || 5000;
const MONGO = process.env.MONGODB_URI || 'mongodb+srv://muruganandhamm7639:8PqDNvNTo2GojCif@cluster0.hlroj.mongodb.net/EmployeeDB?retryWrites=true&w=majority&appName=Cluster0';
mongoose.connect(MONGO).then(()=> console.log('MongoDB connected')).catch(e=>console.error(e));
app.use('/api/auth', authRoutes);
app.use('/api/leads', leadsRoutes);
app.use('/api/newsletter', newsletterRoutes);
app.use('/api/admin', adminRoutes);
app.get('/', (req,res)=> res.json({ ok:true }));
app.listen(PORT, ()=> console.log('Server running', PORT));
